// =========================
// 楽曲データ
// =========================
const songData = [
      {
   title: "Lemon (2020.5.2)",
   count: "1",
   type: "cover",
   date: "2020-05-02",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "GuvvGklgiYg",
   start: 1723,
   end: 1777
 },
      {
   title: "ユアハイネス☆マイプリンセス",
   count: "4",
   type: "cover",
   date: "2020-05-01",
   unit: "",
   artist: "ぱんたん",
   singer: "夢追翔、叶、伏見ガク、緑仙",
   video: "LdzXm93GnAg"
 },
      {
   title: "夜もすがら君想ふ(2020.5.1)",
   count: "1",
   type: "cover",
   date: "2020-05-01",
   unit: "",
   artist: "TOKOTOKO(西沢さんP)",
   singer: "夢追翔",
   video: "oxR7yGJ_BuI"
 },
      {
   title: "ラフメイカー(2020.4.25)",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 19299,
   end: 19498
 },
 {
   title: "Flowerwall(2020.4.25)",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 19509,
   end: 19768
 },
 {
   title: "サリシノハラ(2020.4.25)",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "みきとP",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 19800,
   end: 20026
 },
 {
   title: "SAKURAドロップス",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "宇多田ヒカル",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 20074,
   end: 20103
 },
 {
   title: "unravel",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "TK from 凛として時雨",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 20176,
   end: 20212
 },
 {
   title: "abnormalize",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "凛として時雨",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 20215,
   end: 20296
 },
 {
   title: "MASTER OF MUSIC",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "The Cat’s Whiskers",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 20352,
   end: 18877
 },
 {
   title: "BAD BOYZ -悪漢奴等 Underground-",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "悪漢奴等",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 20526,
   end: 20683
 },
 {
   title: "夜もすがら君想ふ(2020.4.25)",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "TOKOTOKO(西沢さんP)",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 20760,
   end: 21433
 },
 {
   title: "惑星ループ",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "ナユタン星人",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 21433,
   end: 21494
 },
 {
   title: "サボテンと蜃気楼",
   count: "1",
   type: "cover",
   date: "2020-04-25",
   unit: "",
   artist: "若干P",
   singer: "夢追翔",
   video: "_5XX4eBAxGE",
   start: 21535,
   end: 21819
 },
      {
   title: "スマイル・エンゲージ",
   count: "3",
   type: "cover",
   date: "2020-04-19",
   unit: "le jouet",
   artist: "Beit",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "jW1lMXtazBc"
 },
      {
   title: "オトノナルホウヘ→",
   count: "4",
   type: "cover",
   date: "2020-04-12",
   unit: "",
   artist: "Goose house",
   singer: "夢追翔、鷹宮リオン、緑仙、レヴィ・エリファ",
   video: "QLCVD3Rxkpg",
   start: 1520,
   end: 1735
 },
      {
   title: "脳裏上のクラッカー",
   count: "1",
   type: "cover",
   date: "2020-04-12",
   unit: "",
   artist: "ずっと真夜中でいいのに。",
   singer: "夢追翔",
   video: "WQw-_nul4sA",
   start: 146,
   end: 414
 },
 {
   title: "公然の秘密",
   count: "1",
   type: "cover",
   date: "2020-04-12",
   unit: "",
   artist: "椎名林檎",
   singer: "夢追翔",
   video: "WQw-_nul4sA",
   start: 463,
   end: 646
 },
 {
   title: "メトロノーム(2020.4.12)",
   count: "1",
   type: "cover",
   date: "2020-04-12",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "WQw-_nul4sA",
   start: 727,
   end: 988
 },
 {
   title: "灰色と青(2020.4.12)",
   count: "1",
   type: "cover",
   date: "2020-04-12",
   unit: "",
   artist: "米津玄師(＋菅田将暉)",
   singer: "夢追翔",
   video: "WQw-_nul4sA",
   start: 1021,
   end: 1351
 },
 {
   title: "スターライト(2020.4.12)",
   count: "1",
   type: "cover",
   date: "2020-04-12",
   unit: "",
   artist: "amazarashi",
   singer: "夢追翔",
   video: "WQw-_nul4sA",
   start: 1418,
   end: 1750
 },
      {
   title: "ドリームレス・ドリームス",
   count: "1",
   type: "cover",
   date: "2020-03-25",
   unit: "",
   artist: "はるまきごはん",
   singer: "夢追翔",
   video: "YiPvzpzdf5Y"
 },
      {
   title: "Playtime Magic(2020.3.18)",
   count: "3",
   type: "original",
   date: "2020-03-18",
   unit: "",
   artist: "加賀美ハヤト / 夢追翔 / 緑仙",
   singer: "夢追翔、加賀美ハヤト、緑仙",
   video: "ERp3QIg9KhA"
 },
      {
   title: "P.F.M.",
   count: "3",
   type: "original",
   date: "2020-03-14",
   unit: "le jouet",
   artist: "le jouet",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "7nzeZYlZVFs"
 },
      {
   title: "天才ロック",
   count: "1",
   type: "cover",
   date: "2020-03-08",
   unit: "",
   artist: "カラスヤサボウ",
   singer: "夢追翔",
   video: "3BmGmihELkI"
 },
      {
   title: "バレンタイン・キッス",
   count: "3",
   type: "cover",
   date: "2020-02-14",
   unit: "",
   artist: "国生さゆり",
   singer: "夢追翔、加賀美ハヤト、緑仙",
   video: "ZKpFOoRMtYs"
 },
      {
   title: "ロメオ -N.Edit-(2020.2.14)",
   count: "3",
   type: "cover",
   date: "2020-02-14",
   unit: "",
   artist: "LIP×LIP(勇次郎・愛蔵 / CV.内山昂輝・島﨑信長)",
   singer: "夢追翔、加賀美ハヤト、緑仙",
   video: "V654oSE_yhE"
 },
      {
   title: "Sweet Devil",
   count: "3",
   type: "cover",
   date: "2020-02-01",
   unit: "",
   artist: "八王子P",
   singer: "夢追翔、緑仙、加賀美ハヤト",
   video: "EkCg_dq_sk4"
 },
      {
   title: "ハッピーバースデートゥーユー",
   count: "1",
   type: "cover",
   date: "2020-01-28",
   unit: "le jouet",
   artist: "-",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "LXDKVE-smX0",
   start: 4751,
   end: 4780
 },
      {
   title: "からくりピエロ",
   count: "3",
   type: "cover",
   date: "2020-01-28",
   unit: "le jouet",
   artist: "40mP",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "EQD91A-7Gvs",
   start: 654,
   end: 928
 },
 {
   title: "白日(2020.1.28)",
   count: "3",
   type: "cover",
   date: "2020-01-28",
   unit: "le jouet",
   artist: "King Gnu",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "EQD91A-7Gvs",
   start: 1729,
   end: 2036
 },
 {
   title: "サリシノハラ(2020.1.28)",
   count: "3",
   type: "cover",
   date: "2020-01-28",
   unit: "le jouet",
   artist: "みきとP",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "EQD91A-7Gvs",
   start: 2117,
   end: 2380
 },
      {
   title: "ピースサイン(2019.12.27)",
   count: "1",
   type: "cover",
   date: "2019-12-27",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "izf9aBpa27Y",
   start: 76,
   end: 311
 },
 {
   title: "馬と鹿",
   count: "1",
   type: "cover",
   date: "2019-12-27",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "izf9aBpa27Y",
   start: 324,
   end: 593
 },
 {
   title: "Lemon (2019.12.27)",
   count: "1",
   type: "cover",
   date: "2019-12-27",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "izf9aBpa27Y",
   start: 675,
   end: 932
 },
 {
   title: "まちがいさがし(2019.12.27)",
   count: "1",
   type: "cover",
   date: "2019-12-27",
   unit: "",
   artist: "菅田将暉",
   singer: "夢追翔",
   video: "izf9aBpa27Y",
   start: 1003,
   end: 1226
 },
 {
   title: "ロングホープ・フィリア",
   count: "1",
   type: "cover",
   date: "2019-12-27",
   unit: "",
   artist: "菅田将暉",
   singer: "夢追翔",
   video: "izf9aBpa27Y",
   start: 1268,
   end: 1563
 },
 {
   title: "死にたくないから生きている(2019.12.27)",
   count: "1",
   type: "original",
   date: "2019-12-27",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "izf9aBpa27Y",
   start: 1584,
   end: 1854
 },
      {
   title: "白い恋人達(2019.12.25)",
   count: "1",
   type: "cover",
   date: "2019-12-25",
   unit: "",
   artist: "桑田佳祐",
   singer: "夢追翔",
   video: "nqunaqX4sOY",
   start: 608,
   end: 882
 },
 {
   title: "クリスマス",
   count: "1",
   type: "cover",
   date: "2019-12-25",
   unit: "",
   artist: "amazarashi",
   singer: "夢追翔",
   video: "nqunaqX4sOY",
   start: 991,
   end: 1092
 },
 {
   title: "クリスマスソング",
   count: "1",
   type: "cover",
   date: "2019-12-25",
   unit: "",
   artist: "back number",
   singer: "夢追翔",
   video: "nqunaqX4sOY",
   start: 1267,
   end: 1437
 },
      {
   title: "Alice in N.Y.",
   count: "3",
   type: "cover",
   date: "2019-12-24",
   unit: "le jouet",
   artist: "ひとしずく×やま△",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "A5o8--ih8Ks"
 },
      {
   title: "夜もすがら君想ふ(2019.12.18)",
   count: "1",
   type: "cover",
   date: "2019-12-18",
   unit: "",
   artist: "TOKOTOKO(西沢さんP)",
   singer: "夢追翔",
   video: "FBItnhsI9do",
   start: 400,
   end: 643
 },
 {
   title: "ロメオ -N.Edit-(2019.12.18)",
   count: "3",
   type: "cover",
   date: "2019-12-18",
   unit: "le jouet",
   artist: "LIP×LIP(勇次郎・愛蔵 / CV.内山昂輝・島﨑信長)",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "FBItnhsI9do",
   start: 1784,
   end: 1974
 },
 {
   title: "Pretender (2019.12.18)",
   count: "3",
   type: "cover",
   date: "2019-12-18",
   unit: "le jouet",
   artist: "Official髭男dism",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "FBItnhsI9do",
   start: 2147,
   end: 2424
 },
 {
   title: "Fire◎Flower",
   count: "3",
   type: "cover",
   date: "2019-12-18",
   unit: "le jouet",
   artist: "halyosy",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "FBItnhsI9do",
   start: 2756,
   end: 3019
 },
      {
   title: "Vital-バイタル-",
   count: "5",
   type: "original",
   date: "2019-11-30",
   unit: "",
   artist: "レンチ",
   singer: "夢追翔、あくまのゴート、飛鳥ひな、朝霞しお、天城てん、歌衣アズミ、歌衣メイカ、歌衣イツミ、家庭用ロボットアイゼン、ギルザレンⅢ世、黒井しば、粛正罰丸、ジョー・力一、白上フブキ、白鷺ネクロ、白百合リリィ、でびでび・でびる、天開司、ドーラ、夏色まつり、花畑チャイカ、ぴろぱる、星月せい、町田ちま、皆守ひいろ、物述有栖、ユキミお姉ちゃん、レンチ",
   video: "BMBK0qEtPTw"
 },
      {
   title: "Go my green days (2019.11.29)",
   count: "4",
   type: "original",
   date: "2019-11-29",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔、鷹宮リオン、でびでび・でびる、緑仙",
   video: "UcCluiu7S60",
   start: 2085,
   end: 2141
 },
      {
   title: "オンリー ロンリー グローリー",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 435,
   end: 716
 },
 {
   title: "メーデー",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 805,
   end: 1149
 },
 {
   title: "ラフメイカー(2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 1286,
   end: 1515
 },
 {
   title: "車輪の唄(2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 1596,
   end: 1865
 },
 {
   title: "才悩人応援歌",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 1996,
   end: 2251
 },
 {
   title: "真っ赤な空を見ただろうか",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 2401,
   end: 2644
 },
 {
   title: "sailing day (2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 2705,
   end: 2944
 },
 {
   title: "天体観測(2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 2952,
   end: 3215
 },
 {
   title: "Rising Hope",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "LiSA",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 3410,
   end: 3667
 },
 {
   title: "光と闇の童話(2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 3775,
   end: 4235
 },
 {
   title: "よだかの星",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 4369,
   end: 4558
 },
 {
   title: "紅蓮の弓矢(2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "Linked Horizon",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 4709,
   end: 5026
 },
 {
   title: "月曜日",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "amazarashi",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 5220,
   end: 5584
 },
 {
   title: "季節は次々死んでいく",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "amazarashi",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 5707,
   end: 6045
 },
 {
   title: "空に歌えば",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "amazarashi",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 6174,
   end: 6401
 },
 {
   title: "たられば",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "amazarashi",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 6487,
   end: 6855
 },
 {
   title: "ウィーアー!(2019.11.28)",
   count: "1",
   type: "cover",
   date: "2019-11-28",
   unit: "",
   artist: "きただにひろし",
   singer: "夢追翔",
   video: "RlMI5n3nPUQ",
   start: 6964,
   end: 7208
 },
      {
   title: "緑仙RAP 〜3Dになる君へ〜",
   count: "1",
   type: "original",
   date: "2019-11-22",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "fYf249KSSBY",
   start: 1325,
   end: 1476
 },
      {
   title: "生きてることが辛いなら",
   count: "1",
   type: "cover",
   date: "2019-11-20",
   unit: "",
   artist: "森山直太朗",
   singer: "夢追翔",
   video: "V6bRBi15d4A",
   start: 1267,
   end: 1284
 },
 {
   title: "未来予想図II",
   count: "1",
   type: "cover",
   date: "2019-11-20",
   unit: "",
   artist: "DREAMS COME TRUE",
   singer: "夢追翔",
   video: "V6bRBi15d4A",
   start: 1824,
   end: 1841
 },
      {
   title: "IMITATION BLACK",
   count: "3",
   type: "cover",
   date: "2019-11-18",
   unit: "le jouet",
   artist: "natsuP",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "sRwiHYfeH4c"
 },
      {
   title: "Mrs.Pumpkinの滑稽な夢(2019.10.31)",
   count: "3",
   type: "cover",
   date: "2019-10-31",
   unit: "le jouet",
   artist: "ハチ",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "XMES2Aj9IQ0"
 },
      {
   title: "歌いながら喋る枠 3",
   count: "1",
   type: "original",
   date: "2019-10-25",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "jGtyyZLeifc",
   start: 0,
   end: 2741
 },
      {
   title: "それが大事",
   count: "3",
   type: "cover",
   date: "2019-10-21",
   unit: "",
   artist: "大事MANブラザーズバンド",
   singer: "夢追翔、黒井しば、郡道美玲",
   video: "2P_tFqyRNrs",
   start: 2333,
   end: 2351
 },
 {
   title: "ひゃくごじゅういち",
   count: "2",
   type: "cover",
   date: "2019-10-21",
   unit: "",
   artist: "オーキド博士(石塚運昇)とポケモンキッズ",
   singer: "夢追翔、黒井しば",
   video: "2P_tFqyRNrs",
   start: 2939,
   end: 2895
 },
      {
   title: "にじのむこうに(2019.10.18)",
   count: "2",
   type: "cover",
   date: "2019-10-18",
   unit: "",
   artist: "速水けんたろう、茂森あゆみ",
   singer: "夢追翔、緑仙",
   video: "ME8sm0f1CmI",
   start: 1484,
   end: 1638
 },
 {
   title: "Go my green days (2019.10.18)",
   count: "1",
   type: "original",
   date: "2019-10-18",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "ME8sm0f1CmI",
   start: 1765,
   end: 1824
 },
      {
   title: "PONPONPON",
   count: "1",
   type: "cover",
   date: "2019-10-09",
   unit: "",
   artist: "きゃりーぱみゅぱみゅ",
   singer: "夢追翔",
   video: "accvoMgXTVU",
   start: 2891,
   end: 2901
 },
      {
   title: "Pretender(2019.9.24)",
   count: "1",
   type: "cover",
   date: "2019-09-24",
   unit: "",
   artist: "Official髭男dism",
   singer: "夢追翔",
   video: "DQqMDc5_034"
 },
      {
   title: "ファンサ",
   count: "5",
   type: "cover",
   date: "2019-09-18",
   unit: "",
   artist: "mona (CV : 夏川椎菜)",
   singer: "夢追翔、赤羽葉子、花畑チャイカ、社築、緑仙",
   video: "NK1po3z2pto"
 },
      {
   title: "メラメラハート",
   count: "4",
   type: "original",
   date: "2019-09-13",
   unit: "NZMN",
   artist: "NZMN",
   singer: "NZMN (夢追翔、卯月コウ、成瀬鳴、春崎エアル)",
   video: "1XM1bSDefkM"
 },
      {
   title: "Shocking Party",
   count: "3",
   type: "cover",
   date: "2019-09-04",
   unit: "le jouet",
   artist: "A-RISE",
   singer: "le jouet (夢追翔、加賀美ハヤト、緑仙)",
   video: "8pvNiT8O0Fc"
 },
      {
   title: "Go my green days(2019.9.2)",
   count: "2",
   type: "original",
   date: "2019-09-02",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔、緑仙",
   video: "gKcUbsUFp6I",
   start: 1373,
   end: 1435
 },
      {
   title: "にじのむこうに(2019.9.2)",
   count: "2",
   type: "cover",
   date: "2019-09-02",
   unit: "",
   artist: "速水けんたろう、茂森あゆみ",
   singer: "夢追翔、緑仙",
   video: "gKcUbsUFp6I",
   start: 618,
   end: 772
 },
      {
   title: "白日(2019.8.31)",
   count: "1",
   type: "cover",
   date: "2019-08-31",
   unit: "",
   artist: "King Gnu",
   singer: "夢追翔",
   video: "ai59f32SMEA"
 },
      {
   title: "違う、そうじゃない",
   count: "1",
   type: "cover",
   date: "2019-08-26",
   unit: "",
   artist: "鈴木雅之",
   singer: "夢追翔",
   video: "FsCl4dB3sHw",
   start: 1812,
   end: 1817
 },
 {
   title: "かあさんの歌",
   count: "1",
   type: "cover",
   date: "2019-08-26",
   unit: "",
   artist: "窪田聡",
   singer: "夢追翔",
   video: "FsCl4dB3sHw",
   start: 2411,
   end: 2424
 },
      {
   title: "まちがいさがし(2019.8.22)",
   count: "1",
   type: "cover",
   date: "2019-08-22",
   unit: "",
   artist: "菅田将暉",
   singer: "夢追翔",
   video: "wN-O4n3UVZU"
 },
      {
   title: "君の知らない物語(2019.8.19)",
   count: "1",
   type: "cover",
   date: "2019-08-19",
   unit: "",
   artist: "supercell",
   singer: "夢追翔",
   video: "BLFO9z_2xO4",
   start: 128,
   end: 469
 },
 {
   title: "ひまわりの約束",
   count: "1",
   type: "cover",
   date: "2019-08-19",
   unit: "",
   artist: "秦基博",
   singer: "夢追翔",
   video: "BLFO9z_2xO4",
   start: 1269,
   end: 1577
 },
 {
   title: "サムライハート",
   count: "1",
   type: "cover",
   date: "2019-08-19",
   unit: "",
   artist: "SPYAIR",
   singer: "夢追翔",
   video: "BLFO9z_2xO4",
   start: 1738,
   end: 1928
 },
 {
   title: "突然",
   count: "1",
   type: "cover",
   date: "2019-08-19",
   unit: "",
   artist: "FIELD OF VIEW",
   singer: "夢追翔",
   video: "BLFO9z_2xO4",
   start: 2436,
   end: 2720
 },
 {
   title: "secret base 〜君がくれたもの〜",
   count: "1",
   type: "cover",
   date: "2019-08-19",
   unit: "",
   artist: "ZONE",
   singer: "夢追翔",
   video: "BLFO9z_2xO4",
   start: 3164,
   end: 3536
 },
      {
   title: "全力少年",
   count: "1",
   type: "cover",
   date: "2019-08-12",
   unit: "",
   artist: "スキマスイッチ",
   singer: "夢追翔",
   video: "66HYhV-z8C0",
   start: 37,
   end: 279
 },
 {
   title: "ガラナ",
   count: "1",
   type: "cover",
   date: "2019-08-12",
   unit: "",
   artist: "スキマスイッチ",
   singer: "夢追翔",
   video: "66HYhV-z8C0",
   start: 519,
   end: 794
 },
 {
   title: "マリンスノウ",
   count: "1",
   type: "cover",
   date: "2019-08-12",
   unit: "",
   artist: "スキマスイッチ",
   singer: "夢追翔",
   video: "66HYhV-z8C0",
   start: 937,
   end: 1257
 },
 {
   title: "奏",
   count: "1",
   type: "cover",
   date: "2019-08-12",
   unit: "",
   artist: "スキマスイッチ",
   singer: "夢追翔",
   video: "66HYhV-z8C0",
   start: 1375,
   end: 1675
 },
 {
   title: "ゴールデンタイムラバー",
   count: "1",
   type: "cover",
   date: "2019-08-12",
   unit: "",
   artist: "スキマスイッチ",
   singer: "夢追翔",
   video: "66HYhV-z8C0",
   start: 1750,
   end: 2088
 },
      {
   title: "歌いながら喋る枠 2",
   count: "1",
   type: "original",
   date: "2019-08-11",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "UWgLcEOJuWI",
   start: 25,
   end: 1926
 },
      {
   title: "ソラニン(にじロック ver. )",
   count: "5",
   type: "cover",
   date: "2019-08-02",
   unit: "にじロック",
   artist: "ASIAN KUNG-FU GENERATION",
   singer: "にじロック(夢追翔、雨森小夜、加賀美ハヤト、三枝明那、ジョー・力一、轟京子、緑仙)",
   video: "nrFKOk4TObg"
 },
      {
   title: "sailing day (2019.8.2)",
   count: "1",
   type: "cover",
   date: "2019-08-02",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "W6UL-ttimj4",
   start: 86,
   end: 321
 },
 {
   title: "天体観測(2019.8.2)",
   count: "1",
   type: "cover",
   date: "2019-08-02",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "W6UL-ttimj4",
   start: 430,
   end: 691
 },
 {
   title: "ロストマン",
   count: "1",
   type: "cover",
   date: "2019-08-02",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "W6UL-ttimj4",
   start: 760,
   end: 1062
 },
 {
   title: "遥か彼方",
   count: "1",
   type: "cover",
   date: "2019-08-02",
   unit: "",
   artist: "ASIAN KUNG-FU GENERATION",
   singer: "夢追翔",
   video: "W6UL-ttimj4",
   start: 1104,
   end: 1344
 },
 {
   title: "リライト",
   count: "1",
   type: "cover",
   date: "2019-08-02",
   unit: "",
   artist: "ASIAN KUNG-FU GENERATION",
   singer: "夢追翔",
   video: "W6UL-ttimj4",
   start: 1399,
   end: 1624
 },
 {
   title: "ソラニン(夢追ソロ ver.)",
   count: "1",
   type: "cover",
   date: "2019-08-02",
   unit: "",
   artist: "ASIAN KUNG-FU GENERATION",
   singer: "夢追翔",
   video: "W6UL-ttimj4",
   start: 1708,
   end: 1980
 },
      {
   title: "HONEY",
   count: "1",
   type: "cover",
   date: "2019-07-31",
   unit: "",
   artist: "L’Arc〜en〜Ciel",
   singer: "夢追翔",
   video: "WqkZxdYDrs0",
   start: 133,
   end: 357
 },
 {
   title: "Killing Me",
   count: "1",
   type: "cover",
   date: "2019-07-31",
   unit: "",
   artist: "L’Arc〜en〜Ciel",
   singer: "夢追翔",
   video: "WqkZxdYDrs0",
   start: 883,
   end: 1124
 },
 {
   title: "New World",
   count: "1",
   type: "cover",
   date: "2019-07-31",
   unit: "",
   artist: "L’Arc〜en〜Ciel",
   singer: "夢追翔",
   video: "WqkZxdYDrs0",
   start: 1248,
   end: 1495
 },
 {
   title: "READY STEADY GO (2019.7.31)",
   count: "1",
   type: "cover",
   date: "2019-07-31",
   unit: "",
   artist: "L’Arc〜en〜Ciel",
   singer: "夢追翔",
   video: "WqkZxdYDrs0",
   start: 1587,
   end: 1813
 },
      {
   title: "シャルルを噛む",
   count: "1",
   type: "cover",
   date: "2019-07-28",
   unit: "",
   artist: "バルーン、ずっと真夜中でいいのに。",
   singer: "夢追翔",
   video: "bY-xavJXqSg"
 },
      {
   title: "仰げば尊し",
   count: "1",
   type: "cover",
   date: "2019-07-14",
   unit: "",
   artist: "-",
   singer: "夢追翔",
   video: "58rKzeF2BJE",
   start: 1831,
   end: 1846
 },
 {
   title: "ね〜え？",
   count: "1",
   type: "cover",
   date: "2019-07-14",
   unit: "",
   artist: "松浦亜弥",
   singer: "夢追翔",
   video: "58rKzeF2BJE",
   start: 2320,
   end: 2329
 },
 {
   title: "home",
   count: "1",
   type: "cover",
   date: "2019-07-14",
   unit: "",
   artist: "木山裕策",
   singer: "夢追翔",
   video: "58rKzeF2BJE",
   start: 1898,
   end: 1907
 },
 {
   title: "TSUNAMI",
   count: "1",
   type: "cover",
   date: "2019-07-14",
   unit: "",
   artist: "サザンオールスターズ",
   singer: "夢追翔",
   video: "58rKzeF2BJE",
   start: 3106,
   end: 3119
 },
      {
   title: "GLAMOROUS SKY (ENGLISH VER.)",
   count: "1",
   type: "cover",
   date: "2019-07-03",
   unit: "",
   artist: "HYDE",
   singer: "夢追翔",
   video: "lOzBqH2OUWU"
 },
      {
   title: "死にたくないから生きている(2019.6.28)",
   count: "1",
   type: "original",
   date: "2019-06-28",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "Vhon1W1jEF8",
   start: 1940,
   end: 2210
 },
 {
   title: "弱きに寄り添う(2019.6.28)",
   count: "1",
   type: "original",
   date: "2019-06-28",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "Vhon1W1jEF8",
   start: 2282,
   end: 2590
 },
 {
   title: "緑仙RAP (ゆめお Birthday Live ver.)",
   count: "1",
   type: "original",
   date: "2019-06-28",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "Vhon1W1jEF8",
   start: 2750,
   end: 2976
 },
 {
   title: "人より上手に(2019.6.28)",
   count: "1",
   type: "original",
   date: "2019-06-28",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "Vhon1W1jEF8",
   start: 3161,
   end: 3466
 },
      {
   title: "語れ！涙！",
   count: "1",
   type: "cover",
   date: "2019-06-27",
   unit: "",
   artist: "SEX MACHINEGUN",
   singer: "夢追翔",
   video: "d4tqYD841eM",
   start: 2689,
   end: 2698
 },
      {
   title: "Yokohama Walker",
   count: "1",
   type: "cover",
   date: "2019-06-19",
   unit: "",
   artist: "MAD TRIGGER CREW",
   singer: "夢追翔",
   video: "E9sX7HdiAtg",
   start: 554,
   end: 795
 },
 {
   title: "DEATH RESPECT",
   count: "1",
   type: "cover",
   date: "2019-06-19",
   unit: "",
   artist: "MAD TRIGGER CREW・麻天狼",
   singer: "夢追翔",
   video: "E9sX7HdiAtg",
   start: 1000,
   end: 1256
 },
 {
   title: "The Champion",
   count: "1",
   type: "cover",
   date: "2019-06-19",
   unit: "",
   artist: "麻天狼",
   singer: "夢追翔",
   video: "E9sX7HdiAtg",
   start: 1466,
   end: 1692
 },
 {
   title: "Hoodstar",
   count: "1",
   type: "cover",
   date: "2019-06-19",
   unit: "",
   artist: "Division All Stars",
   singer: "夢追翔",
   video: "E9sX7HdiAtg",
   start: 1824,
   end: 2181
 },
      {
   title: "人より上手に(2019.6.12)",
   count: "1",
   type: "original",
   date: "2019-06-12",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "1u9ESQRXTMo"
 },
      {
   title: "創聖のアクエリオン",
   count: "1",
   type: "cover",
   date: "2019-05-28",
   unit: "",
   artist: "AKINO",
   singer: "夢追翔",
   video: "og3NMK8Cd7w",
   start: 972,
   end: 1254
 },
 {
   title: "ポニーテールとシュシュ",
   count: "1",
   type: "cover",
   date: "2019-05-28",
   unit: "",
   artist: "AKB48",
   singer: "夢追翔",
   video: "og3NMK8Cd7w",
   start: 1539,
   end: 1806
 },
 {
   title: "First Love",
   count: "1",
   type: "cover",
   date: "2019-05-28",
   unit: "",
   artist: "宇多田ヒカル",
   singer: "夢追翔",
   video: "og3NMK8Cd7w",
   start: 2235,
   end: 2496
 },
 {
   title: "ハナミズキ",
   count: "1",
   type: "cover",
   date: "2019-05-28",
   unit: "",
   artist: "一青窈",
   singer: "夢追翔",
   video: "og3NMK8Cd7w",
   start: 2738,
   end: 3042
 },
 {
   title: "Rising Hope(2019.5.28)",
   count: "1",
   type: "cover",
   date: "2019-05-28",
   unit: "",
   artist: "LiSA",
   singer: "夢追翔",
   video: "og3NMK8Cd7w",
   start: 3235,
   end: 3485
 },
      {
   title: "ギリギリchop",
   count: "1",
   type: "cover",
   date: "2019-05-09",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "e_VEeqTIo2M",
   start: 67,
   end: 303
 },
 {
   title: "OCEAN",
   count: "1",
   type: "cover",
   date: "2019-05-09",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "e_VEeqTIo2M",
   start: 497,
   end: 821
 },
 {
   title: "愛のバクダン",
   count: "1",
   type: "cover",
   date: "2019-05-09",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "e_VEeqTIo2M",
   start: 1000,
   end: 1263
 },
 {
   title: "今夜月の見える丘に(2019.5.9)",
   count: "1",
   type: "cover",
   date: "2019-05-09",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "e_VEeqTIo2M",
   start: 1428,
   end: 1660
 },
 {
   title: "イチブトゼンブ",
   count: "1",
   type: "cover",
   date: "2019-05-09",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "e_VEeqTIo2M",
   start: 1839,
   end: 2088
 },
 {
   title: "ultra soul (2019.5.9)",
   count: "1",
   type: "cover",
   date: "2019-05-09",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "e_VEeqTIo2M",
   start: 2298,
   end: 2518
 },
      {
   title: "完全感覚Dreamer",
   count: "1",
   type: "cover",
   date: "2019-04-19",
   unit: "",
   artist: "ONE OK ROCK",
   singer: "夢追翔",
   video: "0xfkRdHHHRQ"
 },
      {
   title: "歌いながら喋る枠 1",
   count: "1",
   type: "original",
   date: "2019-04-18",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "drS1ainyRww",
   start: 20,
   end: 1966
 },
      {
   title: "ホリデイ(2019.4.9)",
   count: "1",
   type: "cover",
   date: "2019-04-09",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "4c1mTG5pAT0",
   start: 2762,
   end: 2773
 },
      {
   title: "息継ぎラップ",
   count: "1",
   type: "original",
   date: "2019-03-29",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "jYTzDL4WScU",
   start: 3113,
   end: 3147
 },
      {
   title: "ワタリドリ",
   count: "1",
   type: "cover",
   date: "2019-03-27",
   unit: "",
   artist: "Alexandros",
   singer: "夢追翔",
   video: "kuuOPdJnGUU"
 },
      {
   title: "Space Sonic",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "TYo53YDfWjg",
   start: 245,
   end: 451
 },
 {
   title: "Bored Of Everything",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "TYo53YDfWjg",
   start: 664,
   end: 869
 },
 {
   title: "スターフィッシュ",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "TYo53YDfWjg",
   start: 983,
   end: 1199
 },
 {
   title: "Salamander",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "TYo53YDfWjg",
   start: 1296,
   end: 1501
 },
 {
   title: "モンスター",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "TYo53YDfWjg",
   start: 1609,
   end: 1808
 },
      {
   title: "ウキウキWATCHING",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "いいとも青年隊",
   singer: "夢追翔",
   video: "vqNWctme69g",
   start: 5,
   end: 46
 },
 {
   title: "ジターバグ",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "vqNWctme69g",
   start: 224,
   end: 420
 },
 {
   title: "No.13",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "vqNWctme69g",
   start: 598,
   end: 816
 },
 {
   title: "Missing",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "vqNWctme69g",
   start: 1004,
   end: 1209
 },
 {
   title: "風の日",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "vqNWctme69g",
   start: 1333,
   end: 1582
 },
 {
   title: "Good Morning Kids",
   count: "1",
   type: "cover",
   date: "2019-03-25",
   unit: "",
   artist: "ELLEGARDEN",
   singer: "夢追翔",
   video: "vqNWctme69g",
   start: 1703,
   end: 1904
 },
      {
   title: "Get Wild (2019.3.19)",
   count: "1",
   type: "cover",
   date: "2019-03-19",
   unit: "",
   artist: "TM NETWORK",
   singer: "夢追翔",
   video: "jpQYuf-f1nY",
   start: 120,
   end: 142
 },
      {
   title: "翼をください(2019.3.17)",
   count: "5",
   type: "cover",
   date: "2019-03-17",
   unit: "",
   artist: "赤い鳥",
   singer: "夢追翔、飛鳥ひな、遠北千南、出雲霞、宇志海いちご、神田笑一、渋谷ハジメ、ドーラ、町田ちま、童田明治",
   video: "i2-3Icboojw",
   start: 173,
   end: 349
 },
 {
   title: "Get Wild(2019.3.17)",
   count: "1",
   type: "cover",
   date: "2019-03-17",
   unit: "",
   artist: "TM NETWORK",
   singer: "夢追翔",
   video: "i2-3Icboojw",
   start: 991,
   end: 1097
 },
      {
   title: "SAVIOR OF SONG",
   count: "2",
   type: "cover",
   date: "2019-03-14",
   unit: "",
   artist: "ナノ feat.MY FIRST STORY",
   singer: "夢追翔、ぴろぱる",
   video: "f_Vws_7YCGo"
 },
      {
   title: "エロティカ・セブン",
   count: "1",
   type: "cover",
   date: "2019-03-11",
   unit: "",
   artist: "サザンオールスターズ",
   singer: "夢追翔",
   video: "SGj-9M4TrG8",
   start: 252,
   end: 493
 },
 {
   title: "波乗りジョニー",
   count: "1",
   type: "cover",
   date: "2019-03-11",
   unit: "",
   artist: "桑田佳祐",
   singer: "夢追翔",
   video: "SGj-9M4TrG8",
   start: 646,
   end: 915
 },
 {
   title: "白い恋人達(2019.3.11)",
   count: "1",
   type: "cover",
   date: "2019-03-11",
   unit: "",
   artist: "桑田佳祐",
   singer: "夢追翔",
   video: "SGj-9M4TrG8",
   start: 1065,
   end: 1340
 },
 {
   title: "愛と欲望の日々",
   count: "1",
   type: "cover",
   date: "2019-03-11",
   unit: "",
   artist: "サザンオールスターズ",
   singer: "夢追翔",
   video: "SGj-9M4TrG8",
   start: 1554,
   end: 1818
 },
      {
   title: "BELIEVE",
   count: "1",
   type: "cover",
   date: "2019-03-08",
   unit: "",
   artist: "杉本竜一",
   singer: "夢追翔",
   video: "MWfccOW9VdA",
   start: 416,
   end: 626
 },
 {
   title: "Tomorrow",
   count: "1",
   type: "cover",
   date: "2019-03-08",
   unit: "",
   artist: "杉本竜一",
   singer: "夢追翔",
   video: "MWfccOW9VdA",
   start: 764,
   end: 991
 },
 {
   title: "翼をください(2019.3.8)",
   count: "1",
   type: "cover",
   date: "2019-03-08",
   unit: "",
   artist: "赤い鳥",
   singer: "夢追翔",
   video: "MWfccOW9VdA",
   start: 1148,
   end: 1327
 },
 {
   title: "君をのせて",
   count: "1",
   type: "cover",
   date: "2019-03-08",
   unit: "",
   artist: "井上あずみ",
   singer: "夢追翔",
   video: "MWfccOW9VdA",
   start: 1480,
   end: 1679
 },
      {
   title: "かえるの合唱(2019.3.2)",
   count: "4",
   type: "cover",
   date: "2019-03-02",
   unit: "",
   artist: "-",
   singer: "夢追翔、ドーラ、樋口楓、町田ちま",
   video: "CattJ1HAXe8",
   start: 6345,
   end: 6378
 },
      {
   title: "かえるの合唱(2019.2.26)",
   count: "3",
   type: "cover",
   date: "2019-02-26",
   unit: "",
   artist: "-",
   singer: "夢追翔、黒井しば、町田ちま",
   video: "USnLXjcEW9Q",
   start: 912,
   end: 941
 },
 {
   title: "言葉にできない",
   count: "1",
   type: "cover",
   date: "2019-02-26",
   unit: "",
   artist: "小田和正",
   singer: "夢追翔",
   video: "USnLXjcEW9Q",
   start: 1484,
   end: 1496
 },
      {
   title: "辿りつく詩",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 145,
   end: 512
 },
 {
   title: "Ark (2019.2.24)",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 758,
   end: 1087
 },
 {
   title: "光と闇の童話(2019.2.24)",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 1183,
   end: 1636
 },
 {
   title: "硝子の棺で眠る姫君",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 1714,
   end: 2223
 },
 {
   title: "朝と夜の物語(2019.2.24)",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 2366,
   end: 2779
 },
 {
   title: "紅蓮の弓矢(2019.2.24)",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Linked Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 2879,
   end: 3185
 },
 {
   title: "StarDust (2019.2.24)",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 3260,
   end: 3538
 },
 {
   title: "＜ハジマリ＞のChronicle",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 3635,
   end: 3850
 },
 {
   title: "栄光の移動王国 -The Glory Kingdom-",
   count: "5",
   type: "cover",
   date: "2019-02-24",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "yILoj21rY3M",
   start: 3947,
   end: 4159
 },
      {
   title: "READY STEADY GO(2019.2.17)",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "L’Arc〜en〜Ciel",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 409,
   end: 503
 },
 {
   title: "今夜月の見える丘に(2019.2.17)",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "B’z",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 684,
   end: 830
 },
 {
   title: "箒星(2019.2.17)",
   count: "1",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "Mr.Children",
   singer: "夢追翔",
   video: "nOiWsLPnn1s",
   start: 1005,
   end: 1215
 },
 {
   title: "蕾",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "コブクロ",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 1384,
   end: 1700
 },
 {
   title: "栄光の架橋",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "ゆず",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 1816,
   end: 2154
 },
 {
   title: "We Are Never Ever Getting Back Together",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "Taylor Swift",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 2327,
   end: 2563
 },
 {
   title: "Galway Girl",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "Ed Sheeran",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 2816,
   end: 3035
 },
 {
   title: "Poker Face",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "Lady Gaga",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 3162,
   end: 3401
 },
 {
   title: "ハム太郎とっとこうた(2019.2.17)",
   count: "2",
   type: "cover",
   date: "2019-02-17",
   unit: "",
   artist: "ハムちゃんず",
   singer: "夢追翔、ぴろぱる",
   video: "nOiWsLPnn1s",
   start: 3498,
   end: 3640
 },
      {
   title: "朝と夜の物語(2019.2.16)",
   count: "5",
   type: "cover",
   date: "2019-02-16",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "Y7TPE56hV2M",
   start: 22268,
   end: 22680
 },
 {
   title: "Ark(2019.2.16)",
   count: "5",
   type: "cover",
   date: "2019-02-16",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "Y7TPE56hV2M",
   start: 22834,
   end: 23167
 },
 {
   title: "StarDust (2019.2.16)",
   count: "5",
   type: "cover",
   date: "2019-02-16",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "Y7TPE56hV2M",
   start: 23242,
   end: 23513
 },
 {
   title: "紅蓮の弓矢(2019.2.16)",
   count: "5",
   type: "cover",
   date: "2019-02-16",
   unit: "",
   artist: "Linked Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "Y7TPE56hV2M",
   start: 23687,
   end: 23994
 },
 {
   title: "光と闇の童話(2019.2.16)",
   count: "5",
   type: "cover",
   date: "2019-02-16",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔、出雲霞、鈴木勝、ドーラ、ベルモンド・バンデラス",
   video: "Y7TPE56hV2M",
   start: 24207,
   end: 24661
 },
      {
   title: "ミルクティー",
   count: "5",
   type: "original",
   date: "2019-02-15",
   unit: "",
   artist: "レンチ",
   singer: "夢追翔、あくまのゴート、朝霞しお、飛鳥ひな、家庭用ロボアイゼン、黒井しば、さくらみこ、ジョー・力一、白上フブキ、白鷺ネクロ、でびでび・でびる、夏色まつり、ぴろぱる、町田ちま、皆守ひいろ、レンチ",
   video: "uqQLrla5pDI"
 },
      {
   title: "夢見る口溶け(MV)",
   count: "1",
   type: "original",
   date: "2019-02-14",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "eQgINjgYTMo"
 },
      {
   title: "夢見る口溶け",
   count: "1",
   type: "original",
   date: "2019-02-14",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "iFGgwtXV1Ac",
   start: 9297,
   end: 9327
 },
      {
   title: "緑仙RAP",
   count: "1",
   type: "original",
   date: "2019-02-12",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "1BiL4Ot9GmE"
 },
      {
   title: "さくら粉雪ばんばん",
   count: "1",
   type: "cover",
   date: "2019-02-06",
   unit: "",
   artist: "森山直太朗、レミオロメン、きゃりーぱみゅぱみゅ",
   singer: "夢追翔",
   video: "W3QgEKTd4wU",
   start: 1649,
   end: 1908
 },
      {
   title: "前前キセキ",
   count: "1",
   type: "cover",
   date: "2019-02-06",
   unit: "",
   artist: "RADWIMPS、GReeeeN",
   singer: "夢追翔",
   video: "W3QgEKTd4wU",
   start: 245,
   end: 506
 },
 {
   title: "ナチュラルにROCK",
   count: "1",
   type: "cover",
   date: "2019-02-06",
   unit: "",
   artist: "Perfume、ONE OK ROCK",
   singer: "夢追翔",
   video: "W3QgEKTd4wU",
   start: 632,
   end: 819
 },
 {
   title: "Dragonさくら(独唱)",
   count: "1",
   type: "cover",
   date: "2019-02-06",
   unit: "",
   artist: "SEKAI NO OWARI、森山直太朗",
   singer: "夢追翔",
   video: "W3QgEKTd4wU",
   start: 933,
   end: 1156
 },
 {
   title: "bin’t say “lazy”",
   count: "1",
   type: "cover",
   date: "2019-02-06",
   unit: "",
   artist: "猫アレルギー、桜高軽音部",
   singer: "夢追翔",
   video: "W3QgEKTd4wU",
   start: 1310,
   end: 1521
 },
      {
   title: "VS 剣持ラップ",
   count: "1",
   type: "original",
   date: "2019-02-03",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "NHE1BAFwS6M",
   start: 9044,
   end: 9066
 },
      {
   title: "One more time, One more chance",
   count: "3",
   type: "cover",
   date: "2019-01-31",
   unit: "",
   artist: "山崎まさよし",
   singer: "夢追翔、黒井しば、成瀬鳴",
   video: "K4BVcRFNYgk",
   start: 1514,
   end: 1535
 },
 {
   title: "おじゃま虫",
   count: "4",
   type: "cover",
   date: "2019-01-31",
   unit: "",
   artist: "DECO*27",
   singer: "夢追翔、黒井しば、成瀬鳴、春崎エアル",
   video: "K4BVcRFNYgk",
   start: 1944,
   end: 1958
 },
      {
   title: "WAR WAR WAR",
   count: "1",
   type: "cover",
   date: "2019-01-29",
   unit: "",
   artist: "Buster Bros!!!・MAD TRIGGER CREW",
   singer: "夢追翔",
   video: "f6yy4ir0nBY",
   start: 867,
   end: 1134
 },
 {
   title: "BATTLE BATTLE BATTLE",
   count: "1",
   type: "cover",
   date: "2019-01-29",
   unit: "",
   artist: "Fling Posse・麻天狼",
   singer: "夢追翔",
   video: "f6yy4ir0nBY",
   start: 1218,
   end: 1496
 },
 {
   title: "Shibuya Marble Texture -PCCS-",
   count: "1",
   type: "cover",
   date: "2019-01-29",
   unit: "",
   artist: "Fling Posse",
   singer: "夢追翔",
   video: "f6yy4ir0nBY",
   start: 1562,
   end: 1785
 },
      {
    title: "ヒプノシスマイク -Division Rap Battle-",
    count: "1",
    type: "cover",
    date: "2019-01-29",
    unit: "",
    artist: "Division All Stars",
    singer: "夢追翔",
    video: "f6yy4ir0nBY",
    start: 384,
    end: 692
  },
  {
   title: "ラプラスにのって",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "カスミ(飯塚雅弓)・ラプラス(愛河里花子)",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 1159,
   end: 1343
 },
 {
   title: "ピカチュウのうた",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "ピカチュウ(大谷育江)",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 1384,
   end: 1607
 },
 {
   title: "ライバル！",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "松本梨香",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 1667,
   end: 1878
 },
 {
   title: "Together",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "あきよしふみえ",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 2090,
   end: 2181
 },
 {
   title: "ポケットにファンタジー",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "さち＆じゅり",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 2268,
   end: 2519
 },
 {
   title: "ぼくのベストフレンドへ",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "岩崎宏美",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 2653,
   end: 2859
 },
 {
   title: "ポケモン言えるかな？",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "イマクニ？",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 2926,
   end: 3199
 },
  {
   title: "めざせポケモンマスター",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "松本梨香",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 338,
   end: 590
 },
 {
   title: "ピカピカまっさいチュウ",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "ポケモンキッズ、オーキド博士(＋ピカチュウ)",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 672,
   end: 783
 },
 {
   title: "ニャースのうた",
   count: "5",
   type: "cover",
   date: "2019-01-06",
   unit: "",
   artist: "ニャース(犬山イヌコ)",
   singer: "夢追翔、天城てん、夏色まつり、ぴろぱる、星月せい",
   video: "m-Z4demACxc",
   start: 936,
   end: 1038
 },
  {
   title: "丸ノ内サディスティック",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "椎名林檎",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 2372,
   end: 2599
 },
 {
   title: "Flamingo",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 2712,
   end: 2953
 },
 {
   title: "ハム太郎とっとこうた(2018.12.29)",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "ハムちゃんず",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 3020,
   end: 3139
 },
 {
   title: "Lemon (2018.12.29)",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 3206,
   end: 3487
 },
 {
   title: "ultra soul(2018.12.29)",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "B’z",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 3509,
   end: 3714
 },
  {
   title: "雪の華(2018.12.29)",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "中島美嘉",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 397,
   end: 689
 },
 {
   title: "粉雪(2018.12.29)",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "レミオロメン",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 733,
   end: 1045
 },
 {
   title: "少年時代",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "井上陽水",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 1097,
   end: 1327
 },
 {
   title: "ホール・ニュー・ワールド",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "ピーボ・ブライソン、レジーナ・ベル",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 1389,
   end: 1546
 },
 {
   title: "白虎野の娘",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "平沢進",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 1637,
   end: 1948
 },
 {
   title: "いつかのメリークリスマス(2018.12.29)",
   count: "5",
   type: "cover",
   date: "2018-12-29",
   unit: "",
   artist: "B’z",
   singer: "夢追翔、あくまのゴート、ジョー・力一、皆守ひいろ、レンチ",
   video: "Vl45fbDBxBI",
   start: 2062,
   end: 2317
 },
  {
   title: "ROLL",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 222,
   end: 513
 },
 {
   title: "メリッサ(2018.12.27)",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 622,
   end: 896
 },
 {
   title: "ヒトリノ夜",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 1018,
   end: 1263
 },
 {
   title: "ハネウマライダー",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 1523,
   end: 1810
 },
 {
   title: "ミュージック・アワー",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 1857,
   end: 2132
 },
 {
   title: "愛が呼ぶほうへ",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 2270,
   end: 2529
 },
 {
   title: "Winding Road",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 2565,
   end: 2860
 },
 {
   title: "ジョバイロ",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 2936,
   end: 3196
 },
 {
   title: "アゲハ蝶",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 3237,
   end: 3517
 },
 {
   title: "サウダージ",
   count: "1",
   type: "cover",
   date: "2018-12-27",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "HXGJHAeIUJA",
   start: 3521,
   end: 3782
 },
  {
   title: "新世界",
   count: "5",
   type: "cover",
   date: "2018-12-25",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、あくまのゴート、朝霞しお、飛鳥ひな、天城てん、黒井しば、さくらみこ、ジョー・力一、白上フブキ、でびでび・でびる、春崎エアル、ぴろぱる、ふくやマスター、星月せい、町田ちま、皆守ひいろ、レンチ",
   video: "0yeg4XkzrMI"
 },
  {
   title: "いつかのメリークリスマス(2018.12.24)",
   count: "1",
   type: "cover",
   date: "2018-12-24",
   unit: "",
   artist: "B’z",
   singer: "夢追翔",
   video: "Lvuq_Vcdz_U"
 },
  {
   title: "砂の惑星",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "ハチ",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 239,
   end: 477
 },
 {
   title: "プロトディスコ",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "ぬゆり",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 709,
   end: 974
 },
 {
   title: "エンヴィキャットウォーク",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "トーマ",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 1129,
   end: 1352
 },
 {
   title: "天ノ弱",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "164",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 1497,
   end: 1683
 },
 {
   title: "シャルル(2018.12.19)",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "バルーン",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 1824,
   end: 2053
 },
 {
   title: "花瓶に触れた",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "バルーン",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 2245,
   end: 2465
 },
 {
   title: "あっかんべーだ",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "瀬名航",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 2600,
   end: 2774
 },
 {
   title: "DOGS",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "yukkedoluce",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 2863,
   end: 3097
 },
 {
   title: "ジーニー",
   count: "1",
   type: "cover",
   date: "2018-12-19",
   unit: "",
   artist: "164",
   singer: "夢追翔",
   video: "e8hfHiXRvuE",
   start: 3121,
   end: 3407
 },
  {
   title: "クリスマス・イブ",
   count: "1",
   type: "cover",
   date: "2018-12-17",
   unit: "",
   artist: "山下達郎",
   singer: "夢追翔",
   video: "nU_d6hMi2Y0",
   start: 3291,
   end: 3341
 },
  {
   title: "やさしくなりたい",
   count: "1",
   type: "cover",
   date: "2018-12-13",
   unit: "",
   artist: "斉藤和義",
   singer: "夢追翔",
   video: "p1iRBF9ryrE",
   start: 2135,
   end: 2143
 },
  {
   title: "RAGE OF DUST (2018.12.12)",
   count: "2",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "SPYAIR",
   singer: "夢追翔、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 365,
   end: 546
 },
 {
   title: "ピースサイン(2018.12.12)",
   count: "3",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔、あくまのゴート、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 679,
   end: 962
 },
 {
   title: "カサブタ(2018.12.12)",
   count: "3",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "千綿ヒデノリ",
   singer: "夢追翔、あくまのゴート、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 1192,
   end: 1384
 },
 {
   title: "GO!!!",
   count: "3",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "FLOW",
   singer: "夢追翔、あくまのゴート、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 1613,
   end: 1890
 },
 {
   title: "ロキ",
   count: "3",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "みきとP",
   singer: "夢追翔、あくまのゴート、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 1969,
   end: 2239
 },
 {
   title: "おしゃかしゃま(2018.12.12)",
   count: "3",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、あくまのゴート、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 2399,
   end: 2672
 },
 {
   title: "Butter-Fly",
   count: "3",
   type: "cover",
   date: "2018-12-12",
   unit: "",
   artist: "和田光司",
   singer: "夢追翔、あくまのゴート、ぴろぱる",
   video: "NwrAAnw0nrg",
   start: 2870,
   end: 3118
 },
  {
   title: "瞳をとじて(2018.12.8)",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "平井堅",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 1,
   end: 37
 },
 {
   title: "青いベンチ(2018.12.8)",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "サスケ",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 37,
   end: 76
 },
 {
   title: "粉雪(2018.12.8)",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "レミオロメン",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 76,
   end: 111
 },
 {
   title: "箒星",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "Mr.Children",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 111,
   end: 151
 },
 {
   title: "キセキ",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "GReeeeN",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 151,
   end: 182
 },
 {
   title: "恋",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "星野源",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 182,
   end: 215
 },
 {
   title: "アイネクライネ(2018.12.8)",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 215,
   end: 251
 },
 {
   title: "メリッサ(2018.12.8)",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "ポルノグラフィティ",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 251,
   end: 287
 },
 {
   title: "3月9日",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "レミオロメン",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 287,
   end: 326
 },
 {
   title: "天体観測(2018.12.8)",
   count: "1",
   type: "cover",
   date: "2018-12-08",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔",
   video: "cZp1bB-GU10",
   start: 326,
   end: 361
 },
  {
   title: "弱きに寄り添う(2018.12.6)",
   count: "1",
   type: "original",
   date: "2018-12-06",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "Z2ZO4Ah95H0"
 },
  {
   title: "おねがいダーリン",
   count: "5",
   type: "cover",
   date: "2018-11-29",
   unit: "",
   artist: "ナナホシ管弦楽団",
   singer: "夢追翔、あくまのゴート、七面タキ、ぴろぱる、美影ルクス",
   video: "8ZOCLuXcktk",
   start: 3638,
   end: 3722
 },
  {
   title: "隙間風に吹かれて(2018.11.24)",
   count: "1",
   type: "original",
   date: "2018-11-24",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "H4-PBeOFjLo"
 },
  {
   title: "隙間風に吹かれて(2018.11.22)",
   count: "1",
   type: "original",
   date: "2018-11-22",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "coegyEgGY58",
   start: 3651,
   end: 3676
 },
  {
   title: "夢番地",
   count: "1",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔",
   video: "xJoKjGD8zGA",
   start: 79,
   end: 177
 },
 {
   title: "最大公約数",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 830,
   end: 1062
 },
 {
   title: "揶揄",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 1163,
   end: 1330
 },
 {
   title: "セプテンバーさん",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 1407,
   end: 1670
 },
 {
   title: "イーディーピー 〜飛んで火に入る夏の君〜",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 1790,
   end: 1946
 },
 {
   title: "おしゃかしゃま(2018.11.16)",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 2069,
   end: 2281
 },
 {
   title: "君と羊と青",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 2518,
   end: 2690
 },
 {
   title: "前前前世",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 2796,
   end: 3105
 },
 {
   title: "ジェニファー山田さん",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 3315,
   end: 3527
 },
  {
   title: "空も飛べるはず",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "スピッツ",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 2546,
   end: 2816
 },
 {
   title: "青いベンチ(2018.11.12)",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "サスケ",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 2941,
   end: 3220
 },
 {
   title: "高嶺の花子さん(2018.11.12)",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "back number",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 3324,
   end: 3617
 },
 {
   title: "死にたくないから生きている(2018.11.12)",
   count: "1",
   type: "original",
   date: "2018-11-12",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 3623,
   end: 3894
 },
  {
   title: "雪の華(2018.11.12)",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "中島美嘉",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 474,
   end: 754
 },
 {
   title: "カサブタ(2018.11.12)",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "千綿ヒデノリ",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 1066,
   end: 1261
 },
 {
   title: "ヒプノシスマイク -Division Battle Anthem-",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "Division All Stars",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 1495,
   end: 1816
 },
 {
   title: "瞳をとじて(2018.11.12)",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "平井堅",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 2045,
   end: 2382
 },
             {
    title: "高嶺の花子さん(2018.11.10)",
    count: "1",
    type: "cover",
    date: "2018-11-10",
    unit: "",
    artist: "back number",
    singer: "夢追翔",
    video: "7lYjfAgaTXw"
  },
           {
    title: "燃やし尽くしてナポリタン",
    count: "2",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔、ぴろぱる",
    video: "9TBGaPwP8fs",
    start: 1209,
    end: 1294
  },
  {
    title: "振り返るな黒毛和牛",
    count: "2",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔、ぴろぱる",
    video: "9TBGaPwP8fs",
    start: 2354,
    end: 2446
  },
  {
    title: "来来来世まで",
    count: "1",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔",
    video: "9TBGaPwP8fs",
    start: 3444,
    end: 3517
  },
  {
    title: "振り向くな黒毛和牛",
    count: "2",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔、ぴろぱる",
    video: "9TBGaPwP8fs",
    start: 3824,
    end: 3918
  },
       {
    title: "君の知らない物語(2018.10.27)",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "supercell",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 297,
    end: 665
  },
  {
    title: "いぬのおまわりさん",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
         artist: "-",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 737,
    end: 831
  },
  {
    title: "ちくわパフェだよ☆CKP",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "日向美ビタースイーツ",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 968,
    end: 1088
  },
  {
    title: "打上花火",
    count: "5",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "DAOKO × 米津玄師",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる、町田ちま",
    video: "V7LegYTNQwQ",
    start: 1810,
    end: 2090
  },
  {
    title: "ハム太郎とっとこうた",
    count: "5",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "ハムちゃんず",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる、町田ちま",
    video: "V7LegYTNQwQ",
    start: 2172,
    end: 2274
  },
  {
    title: "じょいふる",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "いきものがかり",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 2408,
    end: 2568
  },
  {
    title: "おら東京さ行ぐだ",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "吉幾三",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 2716,
    end: 2752
  },
  {
    title: "ウィーアー!(2018.10.27)",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "きただにひろし",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 2829,
    end: 2946
  },
  {
    title: "ようこそジャパリパークへ",
    count: "5",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "どうぶつビスケッツ×PPP",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる、町田ちま",
    video: "V7LegYTNQwQ",
    start: 3406,
    end: 3648
  },
     {
    title: "Mrs.Pumpkinの滑稽な夢(2018.10.25)",
    count: "1",
    type: "cover",
    date: "2018-10-25",
    unit: "",
    artist: "ハチ",
    singer: "夢追翔",
    video: "bTwUWwDlVgM"
  },
   {
   title: "ラフメイカー(2018.10.24)",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 336,
   end: 575
 },
 {
   title: "ガラスのブルース",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 714,
   end: 1053
 },
 {
   title: "車輪の唄(2018.10.24)",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 1146,
   end: 1430
 },
 {
   title: "ホリデイ(2018.10.24)",
   count: "4",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 1490,
   end: 1695
 },
 {
   title: "ハルジオン",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 1781,
   end: 2053
 },
 {
   title: "天体観測(2018.10.24)",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 2130,
   end: 2366
 },
 {
   title: "sailing day(2018.10.24)",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 2465,
   end: 2701
 },
 {
   title: "スノースマイル",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 2813,
   end: 3119
 },
 {
   title: "ray(2018.10.24)",
   count: "3",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、七面タキ、ぴろぱる",
   video: "i-ifurGWwjo",
   start: 3164,
   end: 3438
 },
 {
   title: "星のアルペジオ",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 3570,
   end: 3740
 },
   {
   title: "Lemon(2018.10.14)",
   count: "5",
   type: "cover",
   date: "2018-10-14",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔、名伽尾アズマ、花畑チャイカ、社築、緑仙",
   video: "pSO224C09sA",
   start: 1069,
   end: 1163
 },
   {
   title: "RAGE OF DUST(2018.10.14)",
   count: "1",
   type: "cover",
   date: "2018-10-14",
   unit: "",
   artist: "SPYAIR",
   singer: "夢追翔",
   video: "iXBBkDQ12YY"
 },
   {
   title: "アイネクライネ(2018.10.10)",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 208,
   end: 462
 },
 {
   title: "orion",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 615,
   end: 861
 },
 {
   title: "駄菓子屋商売",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 1074,
   end: 1236
 },
 {
   title: "メトロノーム(2018.10.10)",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 1315,
   end: 1557
 },
 {
   title: "恋と病熱",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 1677,
   end: 1913
 },
 {
   title: "Flowerwall(2018.10.10)",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 2026,
   end: 2299
 },
 {
   title: "ピースサイン(2018.10.10)",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 2467,
   end: 2703
 },
 {
   title: "LOSER",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 2769,
   end: 2967
 },
 {
   title: "灰色と青(2018.10.10)",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師(＋菅田将暉)",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 3090,
   end: 3408
 },
 {
   title: "Blue Jasmine",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 3511,
   end: 3759
 },
   {
   title: "さくら(独唱)",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "森山直太朗",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 1523,
   end: 1729
 },
 {
   title: "pride",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "速水ヒロ(前野智昭)",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 2596,
   end: 2671
 },
 {
   title: "StarDust(2018.10.8)",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 3137,
   end: 3373
 },
 {
   title: "EZ DO DANCE -K.O.P. RIMIX-",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "仁科カヅキ(増田俊樹) VS 大和アレクサンダー(武内駿輔)",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 3489,
   end: 3670
 },
   {
   title: "シャルル(2018.10.7)",
   count: "1",
   type: "cover",
   date: "2018-10-07",
   unit: "",
   artist: "バルーン",
   singer: "夢追翔",
   video: "GohYP5pjg5Q",
   start: 722,
   end: 740
 },
   {
 title: "この街で生きている",
 count: "1",
 type: "cover",
 date: "2018-10-04",
 unit: "",
 artist: "amazarashi",
 singer: "夢追翔",
 video: "ssh61KTPksk",
 start: 3422,
 end: 3789
},
   {
 title: "僕が死のうと思ったのは",
 count: "1",
 type: "cover",
 date: "2018-10-04",
 unit: "",
 artist: "amazarashi",
 singer: "夢追翔",
 video: "ssh61KTPksk",
 start: 2982,
 end: 3278
}
   ,
{
title: "ナモナキヒト",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 2535,
end: 2798
},
{
title: "パーフェクトライフ",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 2080,
end: 2318
},
{
title: "ジュブナイル",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 1713,
end: 1929
},
{
title: "スターライト(2018.10.4)",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 1278,
end: 1520
},
{
title: "名前",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 850,
end: 1135
}
   ,
{
title: "風に流離い",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 473,
end: 668
},
{
title: "デビルマンのうた",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "十田敬三",
singer: "夢追翔",
video: "pZ7MEw0bqEw",
start: 2,
end: 41
},
{
title: "Lemon(2018.10.1)",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "米津玄師",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 3449,
end: 3702
},
{
title: "ray(2018.10.1)",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "BUMP OF CHICKEN",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 3037,
end: 3272
},
{
title: "ベンチとコーヒー",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "BUMP OF CHICKEN",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 2611,
end: 2920
}
   ,
{
title: "死にたくないから生きている(2018.9.25)",
count: "1",
type: "original",
date: "2018-09-25",
unit: "",
artist: "夢追翔",
singer: "夢追翔",
video: "XVVXrJQQuNs"
},
{
title: "Lemon(2018.9.29)",
count: "1",
type: "cover",
date: "2018-09-29",
unit: "",
artist: "米津玄師",
singer: "夢追翔",
video: "RUJEeuX_Ac0"
},
{
title: "Replace to be",
count: "5",
type: "original",
date: "2026-05-08",
unit: "VACHSS",
artist: "VACHSS",
singer: "VACHSS (夢追翔、加賀美ハヤト、叶、葛葉、剣持刀也、不破湊)",
video: "7qGbqQTn6og"
},
{
title: "vivi",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "米津玄師",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 2327,
end: 2520
}
];
