// =========================
// 楽曲データ
// =========================
const songData = [
  {
   title: "隙間風に吹かれて",
   count: "1",
   type: "original",
   date: "2018-11-22",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "coegyEgGY58",
   start: 3651,
   end: 3676
 },
  {
   title: "夢番地",
   count: "1",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔",
   video: "xJoKjGD8zGA",
   start: 79,
   end: 177
 },
 {
   title: "最大公約数",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 830,
   end: 1062
 },
 {
   title: "揶揄",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 1163,
   end: 1330
 },
 {
   title: "セプテンバーさん",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 1407,
   end: 1670
 },
 {
   title: "イーディーピー 〜飛んで火に入る夏の君〜",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 1790,
   end: 1946
 },
 {
   title: "おしゃかしゃま",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 2069,
   end: 2281
 },
 {
   title: "君と羊と青",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 2518,
   end: 2690
 },
 {
   title: "前前前世",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 2796,
   end: 3105
 },
 {
   title: "ジェニファー山田さん",
   count: "3",
   type: "cover",
   date: "2018-11-16",
   unit: "",
   artist: "RADWIMPS",
   singer: "夢追翔、ぴろぱる、美影ルクス",
   video: "xJoKjGD8zGA",
   start: 3315,
   end: 3527
 },
  {
   title: "空も飛べるはず",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "スピッツ",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 2546,
   end: 2816
 },
 {
   title: "青いベンチ",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "サスケ",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 2941,
   end: 3220
 },
 {
   title: "高嶺の花子さん(2018.11.12)",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "back number",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 3324,
   end: 3617
 },
 {
   title: "死にたくないから生きている(2018.11.12)",
   count: "1",
   type: "original",
   date: "2018-11-12",
   unit: "",
   artist: "夢追翔",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 3623,
   end: 3894
 },
  {
   title: "雪の華",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "中島美嘉",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 474,
   end: 754
 },
 {
   title: "カサブタ",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "千綿ヒデノリ",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 1066,
   end: 1261
 },
 {
   title: "ヒプノシスマイク -Division Battle Anthem-",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "Division All Stars",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 1495,
   end: 1816
 },
 {
   title: "瞳をとじて",
   count: "1",
   type: "cover",
   date: "2018-11-12",
   unit: "",
   artist: "平井堅",
   singer: "夢追翔",
   video: "N7KnEH8mC-Q",
   start: 2045,
   end: 2382
 },
             {
    title: "高嶺の花子さん(2018.11.10)",
    count: "1",
    type: "cover",
    date: "2018-11-10",
    unit: "",
    artist: "back number",
    singer: "夢追翔",
    video: "7lYjfAgaTXw"
  },
           {
    title: "燃やし尽くしてナポリタン",
    count: "2",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔、ぴろぱる",
    video: "9TBGaPwP8fs",
    start: 1209,
    end: 1294
  },
  {
    title: "振り返るな黒毛和牛",
    count: "2",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔、ぴろぱる",
    video: "9TBGaPwP8fs",
    start: 2354,
    end: 2446
  },
  {
    title: "来来来世まで",
    count: "1",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔",
    video: "9TBGaPwP8fs",
    start: 3444,
    end: 3517
  },
  {
    title: "振り向くな黒毛和牛",
    count: "2",
    type: "original",
    date: "2018-11-02",
    unit: "",
    artist: "夢追翔、ぴろぱる",
    singer: "夢追翔、ぴろぱる",
    video: "9TBGaPwP8fs",
    start: 3824,
    end: 3918
  },
       {
    title: "君の知らない物語",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "supercell",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 297,
    end: 665
  },
  {
    title: "いぬのおまわりさん",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
         artist: "-",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 737,
    end: 831
  },
  {
    title: "ちくわパフェだよ☆CKP",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "日向美ビタースイーツ",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 968,
    end: 1088
  },
  {
    title: "打上花火",
    count: "5",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "DAOKO × 米津玄師",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる、町田ちま",
    video: "V7LegYTNQwQ",
    start: 1810,
    end: 2090
  },
  {
    title: "ハム太郎とっとこうた",
    count: "5",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "ハムちゃんず",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる、町田ちま",
    video: "V7LegYTNQwQ",
    start: 2172,
    end: 2274
  },
  {
    title: "じょいふる",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "いきものがかり",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 2408,
    end: 2568
  },
  {
    title: "おら東京さ行ぐだ",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "吉幾三",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 2716,
    end: 2752
  },
  {
    title: "ウィーアー!",
    count: "4",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "きただにひろし",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる",
    video: "V7LegYTNQwQ",
    start: 2829,
    end: 2946
  },
  {
    title: "ようこそジャパリパークへ",
    count: "5",
    type: "cover",
    date: "2018-10-27",
    unit: "",
    artist: "どうぶつビスケッツ×PPP",
    singer: "夢追翔、朝霞しお、黒井しば、ぴろぱる、町田ちま",
    video: "V7LegYTNQwQ",
    start: 3406,
    end: 3648
  },
     {
    title: "Mrs.Pumpkinの滑稽な夢",
    count: "1",
    type: "cover",
    date: "2018-10-25",
    unit: "",
    artist: "ハチ",
    singer: "夢追翔",
    video: "bTwUWwDlVgM"
  },
   {
   title: "ラフメイカー",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 336,
   end: 575
 },
 {
   title: "ガラスのブルース",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 714,
   end: 1053
 },
 {
   title: "車輪の唄",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 1146,
   end: 1430
 },
 {
   title: "ホリデイ",
   count: "4",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 1490,
   end: 1695
 },
 {
   title: "ハルジオン",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 1781,
   end: 2053
 },
 {
   title: "天体観測",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 2130,
   end: 2366
 },
 {
   title: "sailing day",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 2465,
   end: 2701
 },
 {
   title: "スノースマイル",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 2813,
   end: 3119
 },
 {
   title: "ray(2018.10.24)",
   count: "3",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、七面タキ、ぴろぱる",
   video: "i-ifurGWwjo",
   start: 3164,
   end: 3438
 },
 {
   title: "星のアルペジオ",
   count: "5",
   type: "cover",
   date: "2018-10-24",
   unit: "",
   artist: "BUMP OF CHICKEN",
   singer: "夢追翔、天城てん、七面タキ、ぴろぱる、星月せい",
   video: "i-ifurGWwjo",
   start: 3570,
   end: 3740
 },
   {
   title: "Lemon(2018.10.14)",
   count: "5",
   type: "cover",
   date: "2018-10-14",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔、名伽尾アズマ、花畑チャイカ、社築、緑仙",
   video: "pSO224C09sA",
   start: 1069,
   end: 1163
 },
   {
   title: "RAGE OF DUST",
   count: "1",
   type: "cover",
   date: "2018-10-14",
   unit: "",
   artist: "SPYAIR",
   singer: "夢追翔",
   video: "iXBBkDQ12YY"
 },
   {
   title: "アイネクライネ",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 208,
   end: 462
 },
 {
   title: "orion",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 615,
   end: 861
 },
 {
   title: "駄菓子屋商売",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 1074,
   end: 1236
 },
 {
   title: "メトロノーム",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 1315,
   end: 1557
 },
 {
   title: "恋と病熱",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 1677,
   end: 1913
 },
 {
   title: "Flowerwall",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 2026,
   end: 2299
 },
 {
   title: "ピースサイン",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 2467,
   end: 2703
 },
 {
   title: "LOSER",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 2769,
   end: 2967
 },
 {
   title: "灰色と青",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師(＋菅田将暉)",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 3090,
   end: 3408
 },
 {
   title: "Blue Jasmine",
   count: "1",
   type: "cover",
   date: "2018-10-10",
   unit: "",
   artist: "米津玄師",
   singer: "夢追翔",
   video: "VgXnCw7-dtY",
   start: 3511,
   end: 3759
 },
   {
   title: "さくら(独唱)",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "森山直太朗",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 1523,
   end: 1729
 },
 {
   title: "pride",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "速水ヒロ(前野智昭)",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 2596,
   end: 2671
 },
 {
   title: "StarDust",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "Sound Horizon",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 3137,
   end: 3373
 },
 {
   title: "EZ DO DANCE -K.O.P. RIMIX-",
   count: "1",
   type: "cover",
   date: "2018-10-08",
   unit: "",
   artist: "仁科カヅキ(増田俊樹) VS 大和アレクサンダー(武内駿輔)",
   singer: "夢追翔",
   video: "Af6bpFjvDZI",
   start: 3489,
   end: 3670
 },
   {
   title: "シャルル",
   count: "1",
   type: "cover",
   date: "2018-10-07",
   unit: "",
   artist: "バルーン",
   singer: "夢追翔",
   video: "GohYP5pjg5Q",
   start: 722,
   end: 740
 },
   {
 title: "この街で生きている",
 count: "1",
 type: "cover",
 date: "2018-10-04",
 unit: "",
 artist: "amazarashi",
 singer: "夢追翔",
 video: "ssh61KTPksk",
 start: 3422,
 end: 3789
},
   {
 title: "僕が死のうと思ったのは",
 count: "1",
 type: "cover",
 date: "2018-10-04",
 unit: "",
 artist: "amazarashi",
 singer: "夢追翔",
 video: "ssh61KTPksk",
 start: 2982,
 end: 3278
}
   ,
{
title: "ナモナキヒト",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 2535,
end: 2798
},
{
title: "パーフェクトライフ",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 2080,
end: 2318
},
{
title: "ジュブナイル",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 1713,
end: 1929
},
{
title: "スターライト",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 1278,
end: 1520
},
{
title: "名前",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 850,
end: 1135
}
   ,
{
title: "風に流離い",
count: "1",
type: "cover",
date: "2018-10-04",
unit: "",
artist: "amazarashi",
singer: "夢追翔",
video: "ssh61KTPksk",
start: 473,
end: 668
},
{
title: "デビルマンのうた",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "十田敬三",
singer: "夢追翔",
video: "pZ7MEw0bqEw",
start: 2,
end: 41
},
{
title: "Lemon(2018.10.1)",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "米津玄師",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 3449,
end: 3702
},
{
title: "ray(2018.10.1)",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "BUMP OF CHICKEN",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 3037,
end: 3272
},
{
title: "ベンチとコーヒー",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "BUMP OF CHICKEN",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 2611,
end: 2920
}
   ,
{
title: "死にたくないから生きている(2018.9.25)",
count: "1",
type: "original",
date: "2018-09-25",
unit: "",
artist: "夢追翔",
singer: "夢追翔",
video: "XVVXrJQQuNs"
},
{
title: "Lemon(2018.9.29)",
count: "1",
type: "cover",
date: "2018-09-29",
unit: "",
artist: "米津玄師",
singer: "夢追翔",
video: "RUJEeuX_Ac0"
},
{
title: "Replace to be",
count: "5",
type: "original",
date: "2026-05-08",
unit: "VACHSS",
artist: "VACHSS",
singer: "VACHSS (夢追翔、加賀美ハヤト、叶、葛葉、剣持刀也、不破湊)",
video: "7qGbqQTn6og"
},
{
title: "vivi",
count: "1",
type: "cover",
date: "2018-10-01",
unit: "",
artist: "米津玄師",
singer: "夢追翔",
video: "58hvRtSPcGg",
start: 2327,
end: 2520
}
];
